"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-06-15 10:23:12.536800Z
"""

from api.core import BaseRepository
from api.option.model import Option


class OptionRepository(BaseRepository):
    def model(self):
        return Option
