"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-06-15 10:23:12.533164Z
"""

from typing import Dict
from flask import request
from api.core import BaseController, constants, utils
from api.develop_device.repository import DevelopDeviceRepository


class DevelopDeviceController(BaseController):
    def __init__(self):
        super().__init__()
        self.develop_device_repository = DevelopDeviceRepository()

    def get(self, _id=None):
        if _id is not None:
            develop_device = self.develop_device_repository.find_by_id(_id)
            if develop_device:
                develop_device = develop_device.as_dict()
            return self.success(data=develop_device)

        args = request.args.to_dict()
        page = int(args.get('page', constants.DEFAULT_PAGE))
        size = int(args.get('size', constants.DEFAULT_PAGE_SIZE))
        develop_devices = self.develop_device_repository.get(page=page, size=size)
        for index, develop_device in enumerate(develop_devices):
            develop_devices[index] = develop_device.as_dict()

        result = utils.paginate_serializer(page=page, size=size, data=develop_devices, data_key_name='develop_devices')
        return self.success(data=result)

    def create(self, data: Dict):
        new_develop_device, errors = self.develop_device_repository.create(data=data)
        if errors:
            return self.error(error=errors)

        return self.success(data=new_develop_device.as_dict())

    def update(self, _id, data: Dict):

        develop_device, errors = self.develop_device_repository.update(_id, data=data)
        if errors:
            return self.error(error=errors)

        if develop_device:
            develop_device = develop_device.as_dict()
        return self.success(data=develop_device)

    def delete(self, _id):
        self.develop_device_repository.delete(_id)
        return self.success(data=[])
