"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-06-11 17:52:02.898332Z
"""

from api.core import BaseModel
from extensions import db


class DevelopDevice(BaseModel):
    __tablename__ = "develop_devices"
    id = db.Column(db.String(45), primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    ip_address = db.Column(db.String(45))
    country = db.Column(db.String(100))
    city = db.Column(db.String(100))
