"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-04-05 07:34:46.424886Z
"""

from api.core import BaseRepository
from api.service.model import Service


class ServiceRepository(BaseRepository):
    def model(self):
        return Service
