"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-06-11 17:52:02.901590Z
"""

from api.core import BaseModel
from extensions import db


class UserProfile(BaseModel):
    __tablename__ = "user_profile"
    user_id = db.Column(db.BigInteger, db.ForeignKey('users.id'), primary_key=True, index=True)
    tax_code = db.Column(db.String(45))
    bank_number = db.Column(db.String(100))
    bank_name = db.Column(db.String(255))
    user = db.relationship('User', uselist=False, primaryjoin='UserProfile.user_id == User.id', backref='user_profiles')
