"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-06-15 10:23:12.536976Z
"""

from api.core import BaseRepository
from api.user_profile.model import UserProfile


class UserProfileRepository(BaseRepository):
    def model(self):
        return UserProfile
