"""empty message

Revision ID: 84b85dbd825e
Revises: 
Create Date: 2021-06-12 00:54:51.833932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84b85dbd825e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('develop_devices',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.String(length=45), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('license_templates',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('options',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit_price', sa.BigInteger(), nullable=False),
    sa.Column('unit_amount', sa.BigInteger(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=45), nullable=False),
    sa.Column('is_active', sa.Integer(), server_default='0', nullable=False),
    sa.Column('user_type', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=45), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('application_configs',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('config', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('application_id', 'user_id')
    )
    op.create_index(op.f('ix_application_configs_application_id'), 'application_configs', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_configs_user_id'), 'application_configs', ['user_id'], unique=False)
    op.create_table('license_template_options',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('license_template_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('unit_price', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['license_template_id'], ['license_templates.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], ),
    sa.PrimaryKeyConstraint('license_template_id', 'option_id')
    )
    op.create_index(op.f('ix_license_template_options_license_template_id'), 'license_template_options', ['license_template_id'], unique=False)
    op.create_index(op.f('ix_license_template_options_option_id'), 'license_template_options', ['option_id'], unique=False)
    op.create_table('licenses',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Integer(), server_default='0', nullable=False),
    sa.Column('actived_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licenses_application_id'), 'licenses', ['application_id'], unique=False)
    op.create_index(op.f('ix_licenses_user_id'), 'licenses', ['user_id'], unique=False)
    op.create_table('user_profile',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tax_code', sa.String(length=45), nullable=True),
    sa.Column('bank_number', sa.String(length=100), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profile_user_id'), 'user_profile', ['user_id'], unique=False)
    op.create_table('devices',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.String(length=45), nullable=False),
    sa.Column('license_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_license_id'), 'devices', ['license_id'], unique=False)
    op.create_table('license_options',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('license_id', sa.BigInteger(), nullable=False),
    sa.Column('option_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('unit_price', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['license_id'], ['licenses.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_license_options_license_id'), 'license_options', ['license_id'], unique=False)
    op.create_index(op.f('ix_license_options_option_id'), 'license_options', ['option_id'], unique=False)
    op.drop_table('seeds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seeds',
    sa.Column('file', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('file'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_license_options_option_id'), table_name='license_options')
    op.drop_index(op.f('ix_license_options_license_id'), table_name='license_options')
    op.drop_table('license_options')
    op.drop_index(op.f('ix_devices_license_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_user_profile_user_id'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_licenses_user_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_application_id'), table_name='licenses')
    op.drop_table('licenses')
    op.drop_index(op.f('ix_license_template_options_option_id'), table_name='license_template_options')
    op.drop_index(op.f('ix_license_template_options_license_template_id'), table_name='license_template_options')
    op.drop_table('license_template_options')
    op.drop_index(op.f('ix_application_configs_user_id'), table_name='application_configs')
    op.drop_index(op.f('ix_application_configs_application_id'), table_name='application_configs')
    op.drop_table('application_configs')
    op.drop_table('users')
    op.drop_table('options')
    op.drop_table('license_templates')
    op.drop_table('develop_devices')
    op.drop_table('applications')
    # ### end Alembic commands ###
