"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-06-11 17:52:02.902009Z
"""

from api.core import BaseModel
from extensions import db, jwt


class User(BaseModel):
    __tablename__ = "users"
    id = db.Column(db.BigInteger, primary_key=True)
    email = db.Column(db.String(50), nullable=False, unique=True)
    password = db.Column(db.String(45), nullable=False)
    is_active = db.Column(db.Integer, nullable=False, server_default='0')
    user_type = db.Column(db.Integer, nullable=False)
    name = db.Column(db.String(100), nullable=False)
    phone_number = db.Column(db.String(45))
    address = db.Column(db.String(500))


@jwt.user_identity_loader
def user_identity_lookup(user):
    return user.id


@jwt.user_lookup_loader
def user_lookup_callback(_jwt_header, jwt_data):
    identity = jwt_data["sub"]
    return User.query.filter_by(id=identity).one_or_none()
