"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-04-05 07:34:46.423143Z
"""

from api.core import BaseModel
from extensions import db


class User(BaseModel):
    __tablename__ = "users"
    id = db.Column(db.BigInteger, primary_key=True)
    username = db.Column(db.String(45), nullable=False, unique=True)
    password = db.Column(db.String(255), nullable=False)
    access_token = db.Column(db.String(255), unique=True)
    is_active = db.Column(db.Boolean, nullable=False, server_default='1')
