"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-04-02 09:15:43.541116Z
"""

from api.core import BaseRepository
from api.user.model import User


class UserRepository(BaseRepository):
    def model(self):
        return User
