"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-06-11 17:52:02.905178Z
"""

from api.core import BaseRepository
from api.device.model import Device


class DeviceRepository(BaseRepository):
    def model(self):
        return Device
