"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-06-15 10:23:12.530058Z
"""

from api.core import BaseModel
from extensions import db


class LicenseTemplateOption(BaseModel):
    __tablename__ = "license_template_options"
    __table_args__ = {
        'extend_existing': True
    }
    license_template_id = db.Column(db.Integer, db.ForeignKey('license_templates.id'), primary_key=True, nullable=False, index=True)
    option_id = db.Column(db.BigInteger, db.ForeignKey('options.id'), primary_key=True, nullable=False, index=True)
    amount = db.Column(db.BigInteger, nullable=False)
    unit_price = db.Column(db.BigInteger, nullable=False)
    license_template = db.relationship('LicenseTemplate', primaryjoin='LicenseTemplateOption.license_template_id == LicenseTemplate.id', backref='license_template_options')
    option = db.relationship('Option', primaryjoin='LicenseTemplateOption.option_id == Option.id', backref='license_template_options')
