"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-06-15 10:23:12.536103Z
"""

from api.core import BaseRepository
from api.license_template_option.model import LicenseTemplateOption


class LicenseTemplateOptionRepository(BaseRepository):
    def model(self):
        return LicenseTemplateOption
