"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-06-11 17:52:02.905556Z
"""

from api.core import BaseRepository
from api.license_template_option.model import LicenseTemplateOption


class LicenseTemplateOptionRepository(BaseRepository):
    def model(self):
        return LicenseTemplateOption
