"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-03-30 04:03:36.842807Z
"""

from typing import Dict
from flask import request
from api.core import BaseController, constants, utils
from api.app.repository import AppRepository


class AppController(BaseController):
    def __init__(self):
        super().__init__()
        self.app_repository = AppRepository()

    def get(self, _id=None):
        if _id is not None:
            app = self.app_repository.find_by_id(_id)
            if app:
                app = app.as_dict()
            return self.success(data=app)

        args = request.args.to_dict()
        page = int(args.get('page', constants.DEFAULT_PAGE))
        size = int(args.get('size', constants.DEFAULT_PAGE_SIZE))
        apps = self.app_repository.get(page=page, size=size)
        for index, app in enumerate(apps):
            apps[index] = app.as_dict()

        result = utils.paginate_serializer(page=page, size=size, data=apps, data_key_name='apps')
        return self.success(data=result)

    def create(self, data: Dict):
        return self.success(data=self.app_repository.create(data=data).as_dict())

    def update(self, _id, data: Dict):
        app = self.app_repository.update(_id, data=data)
        if app:
            app = app.as_dict()
        return self.success(data=app)

    def delete(self, _id):
        self.app_repository.delete(_id)
        return self.success(data=[])
