"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-03-30 04:03:36.839451Z
"""

from api.core import BaseModel
from extensions import db


class App(BaseModel):
    __tablename__ = "apps"
    id = db.Column(db.BigInteger, primary_key=True)
    name = db.Column(db.String(45), nullable=False)
