"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-03-30 04:03:36.844135Z
"""

from api.core import BaseRepository
from api.app.model import App


class AppRepository(BaseRepository):
    def model(self):
        return App
