"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-04-05 07:34:46.424525Z
"""

from api.core import BaseRepository
from api.app.model import App


class AppRepository(BaseRepository):
    def model(self):
        return App
