"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-06-11 17:52:02.898003Z
"""

from api.core import BaseModel
from extensions import db


class Application(BaseModel):
    __tablename__ = "applications"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False, unique=True)
    code = db.Column(db.String(100), nullable=False, unique=True)
    description = db.Column(db.Text, nullable=False)
