"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-06-15 10:23:12.528299Z
"""

from api.core import BaseModel
from extensions import db


class Application(BaseModel):
    __tablename__ = "applications"
    __table_args__ = {
        'extend_existing': True
    }
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False, unique=True)
    code = db.Column(db.String(100), nullable=False, unique=True)
    description = db.Column(db.Text, nullable=False)
