"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-06-15 10:23:12.522505Z
"""

from api.core import BaseModel
from extensions import db


class ApplicationConfig(BaseModel):
    __tablename__ = "application_configs"
    __table_args__ = {
        'extend_existing': True
    }
    id = db.Column(db.BigInteger, primary_key=True)
    application_id = db.Column(db.Integer, db.ForeignKey('applications.id'), nullable=False, index=True)
    user_id = db.Column(db.BigInteger, db.ForeignKey('users.id'), nullable=False, index=True)
    config = db.Column(db.Text)
    application = db.relationship('Application', primaryjoin='ApplicationConfig.application_id == Application.id', backref='application_configs')
    user = db.relationship('User', primaryjoin='ApplicationConfig.user_id == User.id', backref='application_configs')
