"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-06-11 17:52:02.892522Z
"""

from api.core import BaseModel
from extensions import db


class ApplicationConfig(BaseModel):
    __tablename__ = "application_configs"
    application_id = db.Column(db.Integer, db.ForeignKey('applications.id'), primary_key=True, nullable=False, index=True)
    user_id = db.Column(db.BigInteger, db.ForeignKey('users.id'), primary_key=True, nullable=False, index=True)
    config = db.Column(db.Text)
    application = db.relationship('Application', primaryjoin='ApplicationConfig.application_id == Application.id', backref='application_configs')
    user = db.relationship('User', primaryjoin='ApplicationConfig.user_id == User.id', backref='application_configs')
