"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-06-11 17:52:02.905807Z
"""

from api.core import BaseRepository
from api.license_template.model import LicenseTemplate


class LicenseTemplateRepository(BaseRepository):
    def model(self):
        return LicenseTemplate
