"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-06-15 10:23:12.529425Z
"""

from api.core import BaseModel
from extensions import db


class LicenseOption(BaseModel):
    __tablename__ = "license_options"
    __table_args__ = {
        'extend_existing': True
    }
    id = db.Column(db.BigInteger, primary_key=True)
    license_id = db.Column(db.BigInteger, db.ForeignKey('licenses.id'), nullable=False, index=True)
    option_id = db.Column(db.BigInteger, db.ForeignKey('options.id'), nullable=False, index=True)
    amount = db.Column(db.BigInteger, nullable=False)
    unit_price = db.Column(db.BigInteger, nullable=False)
    license = db.relationship('License', primaryjoin='LicenseOption.license_id == License.id', backref='license_options')
    option = db.relationship('Option', primaryjoin='LicenseOption.option_id == Option.id', backref='license_options')
