"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-06-15 10:23:12.535889Z
"""

from api.core import BaseRepository
from api.license_option.model import LicenseOption


class LicenseOptionRepository(BaseRepository):
    def model(self):
        return LicenseOption
