"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-06-15 10:23:12.536618Z
"""

from api.core import BaseRepository
from api.license.model import License


class LicenseRepository(BaseRepository):
    def model(self):
        return License
