"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-06-10 03:55:22.168096Z
"""

from api.core import BaseRepository
from api.user.model import User


class UserRepository(BaseRepository):
    def model(self):
        return User
