from .login.route import *
from .application_config.route import *
from .application.route import *
from .develop_device.route import *
from .device.route import *
from .license_option.route import *
from .license_template_option.route import *
from .license_template.route import *
from .license.route import *
from .option.route import *
from .user_profile.route import *
from .user.route import *
