"""
    Author: Do Quoc Vuong
    Email: vuongtlt13@gmail.com
    Country: VietNam
    Generated by VGenerator
    Created at: 2021-04-02 09:15:43.538326Z
"""

from api.core import BaseModel
from extensions import db


class Company(BaseModel):
    __tablename__ = "companies"
    id = db.Column(db.BigInteger, primary_key=True)
    name = db.Column(db.String(45), nullable=False, unique=True)
